# Generated by Django 5.2.7 on 2025-10-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Activos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipos",
            name="done",
        ),
    ]
