# Generated by Django 5.2.7 on 2025-10-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Activos", "0002_remove_equipos_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipos",
            name="modelo",
            field=models.CharField(default="modelo", max_length=30),
        ),
    ]
