# Generated by Django 5.2.7 on 2025-10-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Activos", "0003_equipos_modelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipos",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipos",
            name="marca",
            field=models.CharField(default="marca", max_length=20),
        ),
        migrations.AddField(
            model_name="equipos",
            name="nombre",
            field=models.CharField(default="nombre", max_length=30),
        ),
    ]
