# Generated by Django 5.2.7 on 2025-10-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Activos", "0004_equipos_done_equipos_marca_equipos_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipos",
            old_name="title",
            new_name="usuario",
        ),
    ]
